/**
 * Registre des thèmes de boutique VesTyless
 * Chaque thème a un identifiant unique, des métadonnées, et un composant associé.
 */

export const THEMES = [
  {
    id: 'theme_00',
    name: 'VesTyle Classique',
    description: 'Le thème original de VesTyle. Style marketplace Alibaba/AliExpress, propre et universel.',
    category: 'Classic',
    emoji: '🏪',
    primaryColor: '#059669',
    accentColor: '#ff5000',
    bgColor: '#F8F9FA',
    font: 'Inter',
    previewGradient: 'linear-gradient(135deg, #059669 0%, #10b981 50%, #ff5000 100%)',
    tags: ['Classique', 'Universel', 'Marketplace', 'Original'],
    idealFor: 'Toutes les boutiques — le thème original VesTyle universel et polyvalent',
  },
  {
    id: 'theme_01',
    name: 'Luxe & Couture',
    description: 'Élégance éditoriale, noir & or. Parfait pour la mode haut de gamme.',
    category: 'Fashion',
    emoji: '👑',
    primaryColor: '#0A0A0A',
    accentColor: '#C9A84C',
    bgColor: '#FAF8F5',
    font: 'Playfair Display',
    previewGradient: 'linear-gradient(135deg, #0A0A0A 0%, #2C2C2C 50%, #C9A84C 100%)',
    tags: ['Luxe', 'Mode', 'Couture', 'Fashion'],
    idealFor: 'Boutiques de mode luxe, prêt-à-porter haut de gamme',
  },
  {
    id: 'theme_02',
    name: 'Beauté & Salon',
    description: 'Rose glamour, doux et féminin. Pour les salons de beauté et cosmétiques.',
    category: 'Beauty',
    emoji: '🌸',
    primaryColor: '#B5325A',
    accentColor: '#D4AF37',
    bgColor: '#FFF5F7',
    font: 'Cormorant Garamond',
    previewGradient: 'linear-gradient(135deg, #FFE4E1 0%, #FFB6C1 50%, #B5325A 100%)',
    tags: ['Beauté', 'Salon', 'Cosmétiques', 'Feminin'],
    idealFor: 'Salons de beauté, cosmétiques, parfums, soins',
  },
  {
    id: 'theme_03',
    name: 'Marché Frais',
    description: 'Vert vif et orange dynamique. Idéal pour épiceries et marchés.',
    category: 'Food',
    emoji: '🛒',
    primaryColor: '#1B7A3A',
    accentColor: '#FF8C00',
    bgColor: '#F0FFF4',
    font: 'Nunito',
    previewGradient: 'linear-gradient(135deg, #1B7A3A 0%, #2ECC71 50%, #FF8C00 100%)',
    tags: ['Épicerie', 'Marché', 'Alimentation', 'Frais'],
    idealFor: 'Épiceries, supermarchés, marchés de produits frais',
  },
  {
    id: 'theme_04',
    name: 'Restaurant & Chef',
    description: 'Atmosphère sombre et dorée. Pour les restaurants et traiteurs.',
    category: 'Restaurant',
    emoji: '🍽️',
    primaryColor: '#D4AF37',
    accentColor: '#8B1A1A',
    bgColor: '#120A00',
    font: 'Lora',
    previewGradient: 'linear-gradient(135deg, #120A00 0%, #3D1C00 50%, #D4AF37 100%)',
    tags: ['Restaurant', 'Traiteur', 'Gastronomie', 'Food'],
    idealFor: 'Restaurants, traiteurs, fast-food, cafés',
  },
  {
    id: 'theme_05',
    name: 'Commerce Pro',
    description: 'Bleu marine et orange professionnel. Pour quincailleries et commerces B2B.',
    category: 'Pro',
    emoji: '🔧',
    primaryColor: '#003087',
    accentColor: '#FF6B00',
    bgColor: '#F4F6F9',
    font: 'Roboto Condensed',
    previewGradient: 'linear-gradient(135deg, #003087 0%, #0052CC 50%, #FF6B00 100%)',
    tags: ['Pro', 'B2B', 'Quincaillerie', 'Commerce'],
    idealFor: 'Quincailleries, supermarchés pro, commerce en gros, matériaux',
  },
];

export const getThemeById = (id) => THEMES.find(t => t.id === id) || THEMES[0];

export default THEMES;
